[package]
name = "sev3n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
axum = { version = "0.7.2" }
tracing-subscriber = "0.3"
tracing = "0.1"